name: 'openhealth_dbt'
version: '1.0.0'

profile: 'openhealth_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  openhealth_dbt:

    staging:
      +schema: bronze
      +materialized: view

    silver:
      +schema: silver
      +materialized: view

    gold:
      +schema: gold
      +materialized: table